### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by Jerakin** [defold/extension-safearea#1]
More explicit to point towards a release than a sha1 and safer than pointing to master directly

**Comment by vlaaad** [comment]
Playing a devil's advocate: there is nothing that can be more explicit than sha, because shas are content based while branches and tags are just names that can point to anything.

**Comment by Jerakin** [comment]
I totally agree, but I was thinking of explicit as in easy to read (and thus stated clearly). It is a lot easier to see what have happened since you last updated if you can compare against versions instead of sha strings. In the end I don't think it matters for this extension as it is a temp fix only.

**Comment by britzl** [comment]
There's a point in having releases though. It makes game.project easier to read and update.

Added a 1.0.0 release: https://github.com/defold/extension-safearea/releases/tag/1.0.0
