### ISSUE TITLE
iPhone get_insets values - real pixels or logical size?

### ISSUE THREAD

**Issue by SkaterDad** [defold/extension-safearea#8]
First time using this, so hopefully I'm not in error here.

Device: iPhone XR.

Expected insets from Stackoverflow comments, would be Top = 44px, Bottom = 34px.

`get_insets()` is returning:
```lua
{ 
  bottom = 68,
  right = 0,
  top = 96,
  left = 0
}
```

Why is the extension multiplying the `view.safeAreaInsets` by the contentScale?  Seems like that returns actual physical pixels, not the logical sizes we'd need for adjusting the GUI?

Removing the `scale` multiples works as expected in my fork (on device).  I can submit a PR for this if you want, or maybe the function could be modified to accept a "scale the pixels" boolean to conditionally multiply depending on your use case?

```lua
{
  right = 0,
  top = 48,
  left = 0,
  bottom = 34
}
```

**Comment by SkaterDad** [comment]
Trying this on Android now with a Pixel 6a.

Once again it felt like the insets returned by the extension were too large, since they are the actual pixels.  When using these values to modify the GUI components, we need to scale the values.

```lua
local width, height = window.get_size()
local config_height = sys.get_config_number("display.height",0)
local scale = config_height/height
local scaled_insets = { top = insets.top * scale, bottom = insets.bottom * scale }
```

This feels like something that should be baked into the extension.  Perhaps have 2 functions?  One that returns inset values in real pixels, and one that is transformed to the GUI scaling (on iOS, that would be removing some code, and on Android some code would need to be added).

Anyone else have experience with this extension and how to use it properly?

**Comment by britzl** [comment]
I don't think we do any additional calculations. The extension will return what the platform APIs are returning.

@AGulev should know more about the details.

**Comment by britzl** [comment]
Ah, no, we apply the glview.layer.contentsScale as well. I can't say for sure if this is good or bad. What are the kind of problems you are running into?

**Comment by SkaterDad** [comment]
I was trying to use the `get_insets` function to adjust the y-position of some GUI components.

The numbers as-is from the extension are too large, since the GUI is scaled, so the components were placed too far down the screen (nearly double the expected offset).

The code in my 2nd post about Android worked pretty well.  It would be useful to have the option in the extension to return the scaled offsets that are appropriate for GUI-space.

**Comment by AGulev** [comment]
I think extension should return numbers as they are because there are too many ways to use them in the game.

Maybe it's too big for your setup, but somebody may use another scale mode (stretch/zoom/fit/without scale at all) for GUI, of wanna use it for the game world.
Coordinates conversation is up to developer.

**Comment by SkaterDad** [comment]
Okay, that's understandable.

Appreciate your time and this extension.

The only thing that's still a bit weird is how Android doesn't have the value ready immediately.  Makes me wonder what their SDK developers were thinking.

I'll close this.  Have a nice weekend!

**Comment by britzl** [comment]
> I think extension should return numbers as they are because there are too many ways to use them in the game.
> 

But then maybe we shouldn't multiply insets by content scale like we do on iOS? And instead give an API where we can query display/content scale.

**Comment by SkaterDad** [comment]
> > I think extension should return numbers as they are because there are too many ways to use them in the game.
> 
> But then maybe we shouldn't multiply insets by content scale like we do on iOS? And instead give an API where we can query display/content scale.

Initially for iOS I removed that scaling in a fork.  This got me the expected offsets for GUI for some reason.

I'll rebuild for iOS today, using the same logic I used for Android, on the official branch, and will report back.

**Comment by SkaterDad** [comment]
Okay I've tested it now on the iPhone XR and Google Pixel 6a.

The extension API is consistent across the two platforms, and the same transformation logic works to "correct" the values for GUI scale on my game.

Maybe it would be good to just add some documentation or an example?  I remember someone posting a similar question on the forum a while back.

**Comment by britzl** [comment]
> Okay I've tested it now on the iPhone XR and Google Pixel 6a.
> 
> The extension API is consistent across the two platforms, and the same transformation logic works to "correct" the values for GUI scale on my game.

Great. This is the most important thing that user code shouldn't contain anything platform specific to handle the insets.

> Maybe it would be good to just add some documentation or an example?

Yes, maybe. How are you using the function in your game?
